call_update:
  name: "Run DynDNS update"
  description: "Calls the DynDNS Manager update URL. If host, port or IP are omitted, the current Home Assistant host, port and IPv4 are used by default."
  fields:
    ha_host:
      name: "Home Assistant host"
      description: "Optional. Defaults to the current Home Assistant hostname."
      required: false
      example: "homeassistant.local"
      selector:
        text:
    ha_port:
      name: "Home Assistant port"
      description: "Optional. Defaults to the current port (usually 8123)."
      required: false
      example: 8123
      selector:
        number:
          min: 1
          max: 65535
          mode: box
    web_username:
      name: "Web username"
      description: "Credentials for web access. If exactly one entry exists, its credentials are used automatically."
      required: false
      selector:
        text:
    web_password:
      name: "Web password"
      description: "Credentials for web access. If exactly one entry exists, its credentials are used automatically."
      required: false
      selector:
        text:
          type: password
    myip:
      name: "IP address"
      description: "Optional. Defaults to the IPv4 resolved from the host."
      required: false
      example: "203.0.113.55"
      selector:
        text:
    timeout:
      name: "Timeout"
      description: "Timeout for the HTTP request in seconds."
      required: false
      example: 10
      selector:
        number:
          min: 1
          max: 300
          mode: box
