call_update:
  name: "Run DynDNS update"
  description: "Call the DynDNS Manager update URL. IPv4/IPv6 are only sent if their checkbox is enabled. If enabled and the textbox is empty, the external address is auto-detected."
  fields:
    ha_host:
      name: "Home Assistant host"
      description: "Optional. Defaults to the current Home Assistant hostname."
      required: false
      example: "homeassistant.local"
      selector:
        text:
    ha_port:
      name: "Home Assistant port"
      description: "Optional. Defaults to the current port (usually 8123)."
      required: false
      example: 8123
      selector:
        number:
          min: 1
          max: 65535
          mode: box
    web_username:
      name: "Web username"
      description: "Credentials for web access. If exactly one entry exists, its credentials are used automatically."
      required: false
      selector:
        text:
    web_password:
      name: "Web password"
      description: "Credentials for web access. If exactly one entry exists, its credentials are used automatically."
      required: false
      selector:
        text:
          type: password
    use_ipv4:
      name: "Use IPv4"
      description: "Enable to include IPv4. If enabled and the field below is empty, the external IPv4 will be auto-detected."
      required: false
      default: false
      selector:
        boolean:
    ipv4:
      name: "IPv4 address"
      description: "Optional. Only used if 'Use IPv4' is enabled. Leave empty to auto-detect external IPv4."
      required: false
      example: "203.0.113.55"
      selector:
        text:
    use_ipv6:
      name: "Use IPv6"
      description: "Enable to include IPv6. If enabled and the field below is empty, the external IPv6 will be auto-detected."
      required: false
      default: false
      selector:
        boolean:
    ipv6:
      name: "IPv6 address"
      description: "Optional. Only used if 'Use IPv6' is enabled. Leave empty to auto-detect external IPv6."
      required: false
      example: "2001:db8::1234"
      selector:
        text:
    timeout:
      name: "Timeout"
      description: "Timeout for the HTTP request in seconds."
      required: false
      example: 10
      selector:
        number:
          min: 1
          max: 300
          mode: box
